version: '3.8'

services:
  api:
    build: 
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 7000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
